### ISSUE TITLE
clipboard2  hasAttribute is not a function     

### ISSUE THREAD

**Issue by freshgeek** [Inndy/vue-clipboard2#143]
"vue-clipboard2": "^0.3.3",
    "element-ui": "^2.15.6",

Uncaught TypeError: t.hasAttribute is not a function
    at t.exports (clipboard.min.js:7:1)
    at f (clipboard.min.js:7:1)
    at s (clipboard.min.js:7:1)
    at r.value (clipboard.min.js:7:1)
    at HTMLButtonElement.eval (clipboard.min.js:7:1)
    at eval (vue-clipboard.js:29:1)

**Comment by Hucy** [comment]
convert copied value from number to string this worked for me
